### ISSUE TITLE
加载失败的LLSE插件无法进行操作

### ISSUE THREAD

**Issue by Yushu2606** [LiteLDev/LiteLoader#512]
### 异常模块

ScriptEngine(脚本引擎)

### 操作系统

Windows Server 2022

### LiteLoader版本

2.3.2

### BDS版本

1.19.2.02

### 发生了什么?

加载失败的LLSE插件无法进行操作

### 复现此问题的步骤

加载插件并失败

### 有关的日志/输出

```shell
ll load plugins\Bazaar.js
19:35:06 ERROR [LiteLoader] Too Few arguments!
    at plugins\Bazaar.js:36:26
    at plugins\Bazaar.js:54:3

19:35:06 ERROR [LiteLoader] In API: McClass::getScoreObjective
19:35:06 ERROR [LiteLoader] In Plugin: Bazaar
19:35:06 ERROR [LiteLoader] Fail in Loading Script Plugin!

19:35:06 ERROR [LiteLoader] Fail to load plugins\Bazaar.js!
19:35:06 ERROR [LiteLoader] In Plugin: Bazaar
19:35:06 ERROR [LiteLoader] Uncaught TypeError: Cannot read property 'displayName' of undefined
    at plugins\Bazaar.js:36:45
    at plugins\Bazaar.js:54:3

19:35:06 ERROR [Server] Fail to load plugin plugins\Bazaar.js
ll load plugins\Bazaar.js
19:36:19 ERROR [Server] Fail to load plugin plugins\Bazaar.js
ll list
19:37:29 INFO [Server] Plugin Lists [4]
19:37:29 INFO [Server] - ScriptEngine-Lua [v2.3.2] (LiteLoader.Lua.dll)
19:37:29 INFO [Server]   Lua ScriptEngine for LiteLoaderBDS
19:37:29 INFO [Server] - LiteLoader.NET [v2.3.2] (LiteLoader.NET.dll)
19:37:29 INFO [Server]   .NET development platform for LiteLoaderBDS
19:37:29 INFO [Server] - ScriptEngine-Js [v2.3.2] (LiteLoader.Js.dll)
19:37:29 INFO [Server]   Javascript ScriptEngine for LiteLoaderBDS
19:37:29 INFO [Server] - Bazaar [v1.0.0] (Bazaar.js)
19:37:29 INFO [Server]   物品集市
19:37:29 INFO [Server]
19:37:29 INFO [Server] * Send command "ll list <Plugin Name>" for more information
ll reload Bazaar
19:37:51 ERROR [Server] Fail to reload plugin <Bazaar>
ll unload Bazaar
19:37:55 ERROR [Server] Fail to unload plugin Bazaar
```

### 插件列表

```shell
无
```

**Comment by yqs112358** [comment]
经过测试此问题不再发生，先关闭Issue，如果有问题可以re-open
