### ISSUE TITLE
`BinaryStream`类实例并没有文档中的函数`writeVec3`

### ISSUE THREAD

**Issue by lgc2333** [LiteLDev/LiteLoader#631]
### 异常模块

ScriptEngine（脚本引擎）

### 操作系统

Windows 11

### LiteLoader版本

2.4.2-patch1

### BDS版本

1.19.10

### 发生了什么?

rt

### 复现此问题的步骤

```js
function getPlaySoundDataPack(sound, position, volume, pitch) {
  // type: 103
  const bs = new BinaryStream();
  // bs.reserve(sound.length + );
  bs.writeString(sound);
  bs.writeVec3(position);
  bs.writeFloat(volume);
  bs.writeFloat(pitch);
  return bs.createPacket(103);
}
```

### 有关的日志/输出

```shell
18:15:40 ERROR [LiteLoader] Uncaught TypeError: bs.writeVec3 is not a function
    at getPlaySoundDataPack (plugins\NbsPlayer.lls.js:143:6) 
    at plugins\NbsPlayer.lls.js:252:11
    at task (plugins\NbsPlayer.lls.js:238:16) 

18:15:40 ERROR [LiteLoader] In Plugin: NbsPlayer
```

**Comment by Jaciezyt** [comment]
已发现问题所在

**Comment by Jaciezyt** [comment]
在版本更新前，您可以用三个writeFloat代替
```js
bs.writeFloat(pos.x);
bs.writeFloat(pos.y);
bs.writeFloat(pos.z);
```

**Comment by dreamguxiang** [comment]
主要这个数据包是x = int，y = uint，z = int，不是float（Vec3）
